use crate::scene::*;
use crate::var_registry::VarEntry;

pub fn emit_draw(scene: &Scene, vars: &[VarEntry]) -> String {
    let mut out = String::from(
        r#"// Auto-generated by gauge-builder. Do not edit by hand.

use crate::vars;

#[cfg(target_arch = "wasm32")]
use msfs::nvg::{self, NvgContext, Color, LineCap, LineJoin, Winding};

pub fn render(
    #[cfg(target_arch = "wasm32")] ctx: &NvgContext,
    #[cfg(not(target_arch = "wasm32"))] _ctx: &(),
    width: f32,
    height: f32,
) {
"#,
    );

    // Fetch all bound vars
    let var_ids: Vec<&str> = vars.iter().map(|v| v.id.as_str()).collect();
    if !var_ids.is_empty() {
        out.push_str("    // — fetch all bound vars —\n");
        for id in &var_ids {
            out.push_str(&format!("    let {id} = vars::get_{id}();\n"));
        }
        out.push('\n');
    }

    // Open frame scope (cfg-gated)
    out.push_str(
        r#"    #[cfg(target_arch = "wasm32")]
    ctx.frame(width, height, 1.0, |ctx| {
"#,
    );

    // Emit all elements
    for el in &scene.elements {
        emit_element(&mut out, el, 2);
    }

    out.push_str("    });\n}\n");
    out
}

fn emit_element(out: &mut String, el: &SceneElement, indent: usize) {
    if !el.visible {
        return;
    }
    let pad = "    ".repeat(indent);

    match &el.kind {
        ElementKind::Rect { x, y, w, h, style } => {
            emit_style_calls(out, style, &pad);
            out.push_str(&format!("{pad}ctx.begin_path();\n"));
            out.push_str(&format!(
                "{pad}ctx.rect({}, {}, {}, {});\n",
                bv(x), bv(y), bv(w), bv(h),
            ));
            emit_fill_stroke(out, style, &pad);
        }
        ElementKind::Circle { cx, cy, r, style } => {
            emit_style_calls(out, style, &pad);
            out.push_str(&format!("{pad}ctx.begin_path();\n"));
            out.push_str(&format!(
                "{pad}ctx.circle({}, {}, {});\n",
                bv(cx), bv(cy), bv(r),
            ));
            emit_fill_stroke(out, style, &pad);
        }
        ElementKind::Arc {
            cx, cy, r, a0, a1, dir, style,
        } => {
            let winding = match dir {
                ArcDir::Cw => "Winding::Cw",
                ArcDir::Ccw => "Winding::Ccw",
            };
            emit_style_calls(out, style, &pad);
            out.push_str(&format!("{pad}ctx.begin_path();\n"));
            out.push_str(&format!(
                "{pad}ctx.arc({}, {}, {}, {}, {}, {});\n",
                bv(cx), bv(cy), bv(r), bv(a0), bv(a1), winding,
            ));
            emit_fill_stroke(out, style, &pad);
        }
        ElementKind::Line {
            x1, y1, x2, y2, style,
        } => {
            emit_style_calls(out, style, &pad);
            out.push_str(&format!("{pad}ctx.begin_path();\n"));
            out.push_str(&format!(
                "{pad}ctx.move_to({}, {});\n",
                bv(x1), bv(y1),
            ));
            out.push_str(&format!(
                "{pad}ctx.line_to({}, {});\n",
                bv(x2), bv(y2),
            ));
            emit_fill_stroke(out, style, &pad);
        }
        ElementKind::Text {
            x, y, content, font_size, font, style,
        } => {
            emit_style_calls(out, style, &pad);
            out.push_str(&format!(
                "{pad}// TODO: ensure font \"{}\" is loaded via ctx.create_font() in Gauge::init\n",
                font,
            ));
            out.push_str(&format!(
                "{pad}ctx.font_size({} as f32);\n",
                bv(font_size),
            ));
            out.push_str(&format!(
                "{pad}ctx.text({} as f32, {} as f32, &format!(\"{{}}\", {}));\n",
                bv(x), bv(y), bv(content),
            ));
        }
        ElementKind::Path { commands, style } => {
            emit_style_calls(out, style, &pad);
            out.push_str(&format!("{pad}ctx.begin_path();\n"));
            for cmd in commands {
                match cmd {
                    PathCmd::MoveTo { x, y } => {
                        out.push_str(&format!(
                            "{pad}ctx.move_to({}, {});\n",
                            bv(x), bv(y),
                        ));
                    }
                    PathCmd::LineTo { x, y } => {
                        out.push_str(&format!(
                            "{pad}ctx.line_to({}, {});\n",
                            bv(x), bv(y),
                        ));
                    }
                    PathCmd::BezierTo {
                        c1x, c1y, c2x, c2y, x, y,
                    } => {
                        out.push_str(&format!(
                            "{pad}ctx.bezier_to({}, {}, {}, {}, {}, {});\n",
                            bv(c1x), bv(c1y), bv(c2x), bv(c2y), bv(x), bv(y),
                        ));
                    }
                    PathCmd::ClosePath => {
                        out.push_str(&format!("{pad}ctx.close_path();\n"));
                    }
                }
            }
            emit_fill_stroke(out, style, &pad);
        }
        ElementKind::Group { children, .. } => {
            for child in children {
                emit_element(out, child, indent);
            }
        }
    }
    out.push('\n');
}

/// Emits ctx.fill_color, ctx.stroke_color, ctx.stroke_width, ctx.line_cap, ctx.line_join
fn emit_style_calls(out: &mut String, style: &NvgStyle, pad: &str) {
    out.push_str(&format!("{pad}ctx.save();\n"));

    if let Some(BoundColor::Rgba(r, g, b, a)) = &style.fill {
        out.push_str(&format!(
            "{pad}ctx.fill_color(Color::rgbaf({:.3}, {:.3}, {:.3}, {:.3}));\n",
            r, g, b, a,
        ));
    }

    if let Some(BoundColor::Rgba(r, g, b, a)) = &style.stroke {
        out.push_str(&format!(
            "{pad}ctx.stroke_color(Color::rgbaf({:.3}, {:.3}, {:.3}, {:.3}));\n",
            r, g, b, a,
        ));
        out.push_str(&format!(
            "{pad}ctx.stroke_width({:.1});\n",
            style.stroke_width,
        ));
    }

    // Line cap
    let cap = match style.line_cap {
        LineCap::Butt => "LineCap::Butt",
        LineCap::Round => "LineCap::Round",
        LineCap::Square => "LineCap::Square",
    };
    out.push_str(&format!("{pad}ctx.line_cap({cap});\n"));

    // Line join
    let join = match style.line_join {
        LineJoin::Miter => "LineJoin::Miter",
        LineJoin::Round => "LineJoin::Round",
        LineJoin::Bevel => "LineJoin::Bevel",
    };
    out.push_str(&format!("{pad}ctx.line_join({join});\n"));
}

/// Emits ctx.fill() and/or ctx.stroke(), then ctx.restore()
fn emit_fill_stroke(out: &mut String, style: &NvgStyle, pad: &str) {
    if style.fill.is_some() {
        out.push_str(&format!("{pad}ctx.fill();\n"));
    }
    if style.stroke.is_some() {
        out.push_str(&format!("{pad}ctx.stroke();\n"));
    }
    out.push_str(&format!("{pad}ctx.restore();\n"));
}

fn bv(v: &BoundValue) -> String {
    match v {
        BoundValue::Literal { value } => format!("{:.1}_f32", value),
        BoundValue::LVar { name } | BoundValue::AVar { name, .. } => {
            format!("{} as f32", name)
        }
        BoundValue::Expr { expr } => format!("/* expr: {} */ 0.0_f32", expr),
    }
}
