use crate::scene::Scene;

pub fn emit_gauge(scene: &Scene) -> String {
    let gauge_name = &scene.gauge_name;
    let struct_name = to_pascal_case(gauge_name);
    let snake_name = gauge_name.replace('-', "_").to_lowercase();

    format!(
        r#"// Auto-generated by gauge-builder. Do not edit by hand.

mod vars;
mod draw;

use msfs::prelude::*;
use msfs::nvg::NvgContext;

pub struct {struct_name} {{
    nvg: Option<NvgContext>,
}}

impl Default for {struct_name} {{
    fn default() -> Self {{
        Self {{ nvg: None }}
    }}
}}

impl Gauge for {struct_name} {{
    fn init(&mut self, ctx: Context, _install: &mut GaugeInstall) -> bool {{
        self.nvg = NvgContext::create(ctx);
        self.nvg.is_some()
    }}

    fn update(&mut self, _ctx: Context, _delta_time: f64) -> bool {{
        true
    }}

    fn draw(&mut self, _ctx: Context, draw: &GaugeDraw) -> bool {{
        if let Some(nvg) = &self.nvg {{
            let width = draw.width() as f32;
            let height = draw.height() as f32;
            draw::render(nvg, width, height);
        }}
        true
    }}

    fn kill(&mut self, _ctx: Context) -> bool {{
        self.nvg = None;
        true
    }}
}}

msfs::export_gauge!({snake_name}, {struct_name});
"#
    )
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + &chars.as_str().to_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}
