use crate::var_registry::{VarEntry, VarKind};

pub fn emit_vars(vars: &[VarEntry]) -> String {
    let mut out = String::from("// Auto-generated by gauge-builder. Do not edit by hand.\n\n");

    if !vars.is_empty() {
        out.push_str("#[cfg(target_arch = \"wasm32\")]\nuse infinity_rs::prelude::*;\n\n");
    }

    for var in vars {
        match var.kind {
            VarKind::LVar => {
                let unit = var.unit.as_deref().unwrap_or("Number");
                out.push_str(&format!(
                    r#"#[cfg(target_arch = "wasm32")]
pub fn get_{id}() -> f64 {{
    match LVar::new("{sim_name}", "{unit}") {{
        Ok(v) => v.get().unwrap_or(0.0),
        Err(_) => 0.0,
    }}
}}
#[cfg(not(target_arch = "wasm32"))]
pub fn get_{id}() -> f64 {{ 0.0 }}

"#,
                    id = var.id,
                    sim_name = var.sim_name,
                    unit = unit,
                ));
            }
            VarKind::AVar => {
                let unit = var.unit.as_deref().unwrap_or("Number");
                let index = var.index.unwrap_or(0);
                if index > 0 {
                    out.push_str(&format!(
                        r#"#[cfg(target_arch = "wasm32")]
pub fn get_{id}() -> f64 {{
    match AVar::new("{sim_name}", "{unit}") {{
        Ok(v) => v.get_indexed(&[{index}]).unwrap_or(0.0),
        Err(_) => 0.0,
    }}
}}
#[cfg(not(target_arch = "wasm32"))]
pub fn get_{id}() -> f64 {{ 0.0 }}

"#,
                        id = var.id,
                        sim_name = var.sim_name,
                        unit = unit,
                        index = index,
                    ));
                } else {
                    out.push_str(&format!(
                        r#"#[cfg(target_arch = "wasm32")]
pub fn get_{id}() -> f64 {{
    match AVar::new("{sim_name}", "{unit}") {{
        Ok(v) => v.get().unwrap_or(0.0),
        Err(_) => 0.0,
    }}
}}
#[cfg(not(target_arch = "wasm32"))]
pub fn get_{id}() -> f64 {{ 0.0 }}

"#,
                        id = var.id,
                        sim_name = var.sim_name,
                        unit = unit,
                    ));
                }
            }
        }
    }

    out
}
